name: Publish package to NPM

on:
  release:
    types: [created]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://registry.npmjs.org'

    - name: Build
      run: make install build

    - name: Publish package to npm
      run: npm publish . --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
